### PR TITLE
PWA changes for fsbolero

### PR DESCRIPTION
**Pull request by zakaluka**
Signed-off-by: zakaluka <znprojects.apps@gmail.com>

### CODE REVIEW

**Comment by zakaluka** [comment]
Do i need to bump `version.json`?  If so, what should the value be?

**Comment by zakaluka** [comment]
Please note that i added the same favicon.ico file as the Blazor template to reduce the noise of errors in console output.

**Comment by zakaluka** [comment]
Second note - I am not sure how to test these changes.  Is there a way to build & install the template locally so it can be tried out?  Or a way to install the appveyor build package?

**Comment by Tarmil** [comment]
Let's leave `version.json` as is. I prefer to have Major.minor version that matches the referenced version of Bolero. The patch version is automatically set.

Good call on the favicon.ico :)

For testing, if you run `.\build.cmd` or `./build.sh`, this will generate the package in the `build` folder. Then you can install it with `dotnet new -i build/Bolero.Templates.<version>.nupkg`.

**Comment by zakaluka** [comment]
Tests 1/4:

- `dotnet new bolero-app --help`

image

- `dotnet new bolero-app -o no_options` (no change expected)

list of all files: image
client fsproj: image
index.html: image
build: image

**Comment by zakaluka** [comment]
Tests 2/4:

- `dotnet new bolero-app -m true -o no_options_minimal -s false`  (no change expected)

list of all files: 
image
client fsproj: 
image
index.html: 
image
build: 
image

**Comment by zakaluka** [comment]
Tests 3/4:

- `dotnet new bolero-app -o default_with_pwa -p` (should include PWA information)

list of all files: 
image
client fsproj: 
image
index.html: 
image
build: 
image

**Comment by zakaluka** [comment]
Tests 4/4:

- `dotnet new bolero-app -o minimal_with_pwa -p -m -s false` (should include PWA information)

list of all files: 
image
client fsproj: 
image
index.html: 
image
build: 
image

- `dotnet new bolero-app --server --hotreload --minimal=false --razor --pwa -o razor_reload_pwa`

list of all files: 
image
client fsproj: 
image
index.html: 
image
build: 
image

**Comment by zakaluka** [comment]
I can't tests service workers completely without deploying to a server due to rather extreme security constraints applied by browsers.  I tried a lot last weekend, and finally gave up and tested with github pages.  However, that only works for client-only apps and i don't think i can run the server on github pages.

If you want me to test anything else, please let me know.

**Comment by zakaluka** [comment]
Please let me know if you need anything else for this change.

**Comment by Tarmil** [comment]
This is all looking good, thanks a lot!

**Pull request merged**
